<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComunaBarrioSeeder extends Seeder
{
    public function run(): void
    {
        $comunas = [
            1 => '1 - POPULAR',
            2 => '2 - SANTA CRUZ',
            3 => '3 - MANRIQUE',
            4 => '4 - ARANJUEZ',
            5 => '5 - CASTILLA',
            6 => '6 - DOCE DE OCTUBRE',
            7 => '7 - ROBLEDO',
            8 => '8 - VILLA HERMOSA',
            9 => '9 - BUENOS AIRES',
            10 => '10 - LA CANDELARIA',
            11 => '11 - LAURELES ESTADIO',
            12 => '12 - LA AMERICA',
            13 => '13 - SAN JAVIER',
            14 => '14 - EL POBLADO',
            15 => '15 - GUAYABAL',
            16 => '16 - BELEN',
        ];

        $comunaIds = [];
        foreach ($comunas as $numero => $descripcion) {
            $id = DB::table('t1_comuna')->insertGetId([
                'descripcion' => $descripcion,
                'estado' => '1',
                'municipio_id' => $this->medellinId(),
            ]);
            $comunaIds[$numero] = $id;
        }

        $barriosPorComuna = [
            1 => [
                'Santo Domingo Savio N°1',
                'Santo Domingo Savio N°2',
                'Popular',
                'Granizal',
                'Moscú N°2',
                'Villa Guadalupe',
                'San Pablo',
                'Aldea Pablo VI',
                'La Esperanza N°2',
                'El Compromiso',
                'La Avanzada',
                'Carpinelo',
            ],
            2 => [
                'La Isla',
                'El Playón de Los Comuneros',
                'Pablo VI',
                'La Frontera',
                'La Francia',
                'Andalucía',
                'Villa del Socorro',
                'Villa Niza',
                'Moscú N°1',
                'Santa Cruz',
                'La Rosa',
            ],
            3 => [
                'La Salle',
                'Las Granjas',
                'Campo Valdés N°2',
                'Santa Inés',
                'El Raizal',
                'El Pomar',
                'Manrique Central N°2',
                'Manrique Oriental',
                'Versalles N°1',
                'Versalles N°2',
                'La Cruz',
                'Oriente',
                'María Cano - Carambolas',
                'San José La Cima N°1',
                'San José La Cima N°2',
            ],
            4 => [
                'Berlín',
                'San Isidro',
                'Palermo',
                'Bermejal - Los Álamos',
                'Moravia',
                'Sevilla',
                'San Pedro',
                'Manrique Central N°1',
                'Campo Valdés N°1',
                'Las Esmeraldas',
                'La Piñuela',
                'Aranjuez',
                'Brasilia',
                'Miranda',
            ],
            5 => [
                'Toscana',
                'Las Brisas',
                'Florencia',
                'Tejelo',
                'Boyacá',
                'Héctor Abad Gómez',
                'Belalcázar',
                'Girardot',
                'Tricentenario',
                'Castilla',
                'Francisco Antonio Zea',
                'Alfonso López',
                'Caribe',
                'El Progreso',
            ],
            6 => [
                'Santander',
                'Doce de Octubre N°1',
                'Doce de Octubre N°2',
                'Pedregal',
                'La Esperanza',
                'San Martín de Porres',
                'Kennedy',
                'Picacho',
                'Picachito',
                'Mirador del Doce',
                'Progreso N°2',
                'El Triunfo',
            ],
            7 => [
                'Cerro El Volador',
                'San Germán',
                'Facultad de Minas U. Nacional',
                'La Pilarica',
                'Bosques de San Pablo',
                'Altamira',
                'Córdoba',
                'López de Mesa',
                'El Diamante',
                'Aures N°1',
                'Aures N°2',
                'Bello Horizonte',
                'Villa Flora',
                'Palenque',
                'Robledo',
                'Cucaracho',
                'Fuente Clara',
                'Santa Margarita',
                'Olaya Herrera',
                'Pajarito',
                'Monteclaro',
                'Nueva Villa de La Iguaná',
            ],
            8 => [
                'Villa Hermosa',
                'La Mansión',
                'San Miguel',
                'La Ladera',
                'Batallón Girardot',
                'Llanaditas',
                'Los Mangos',
                'Enciso',
                'Sucre',
                'El Pinal',
                'Trece de Noviembre',
                'La Libertad',
                'Villatina',
                'San Antonio',
                'Las Estancias',
                'Villa Turbay',
                'La Sierra',
                'Villa Lilliam',
            ],
            9 => [
                'Juan Pablo II',
                'Barrios de Jesús',
                'Bombona N°2',
                'Los Cerros El Vergel',
                'Alejandro Echavarría',
                'Barrio Caicedo',
                'Buenos Aires',
                'Miraflores',
                'Cataluña',
                'La Milagrosa',
                'Gerona',
                'El Salvador',
                'Loreto',
                'Asomadera N°1',
                'Asomadera N°2',
                'Asomadera N°3',
                'Ocho de Marzo',
            ],
            10 => [
                'Prado',
                'Jesús Nazareno',
                'El Chagualo',
                'Estación Villa',
                'San Benito',
                'Guayaquil',
                'Corazón de Jesús',
                'Calle Nueva',
                'Perpetuo Socorro',
                'Barrio Colón',
                'Las Palmas',
                'Bomboná N°1',
                'Boston',
                'Los Ángeles',
                'Villa Nueva',
                'La Candelaria',
                'San Diego',
            ],
            11 => [
                'Carlos E. Restrepo',
                'Suramericana',
                'Naranjal',
                'San Joaquín',
                'Los Conquistadores',
                'Bolivariana',
                'Laureles',
                'Las Acacias',
                'La Castellana',
                'Lorena',
                'El Velódromo',
                'Estadio',
                'Los Colores',
                'Cuarta Brigada',
                'Florida Nueva',
            ],
            12 => [
                'Ferrini',
                'Calasanz',
                'Los Pinos',
                'La América',
                'La Floresta',
                'Santa Lucía',
                'El Danubio',
                'Campo Alegre',
                'Santa Mónica',
                'Barrio Cristóbal',
                'Simón Bolívar',
                'Santa Teresita',
                'Calasanz Parte Alta',
            ],
            13 => [
                'El Pesebre',
                'Blanquizal',
                'Santa Rosa de Lima',
                'Los Alcázares',
                'Metropolitano',
                'La Pradera',
                'Juan XXIII - La Quiebra',
                'San Javier N°2',
                'San Javier N°1',
                'Veinte de Julio',
                'Belencito',
                'Betania',
                'El Corazón',
                'Las Independencias',
                'Nuevos Conquistadores',
                'El Salado',
                'Eduardo Santos',
                'Antonio Nariño',
                'El Socorro',
            ],
            14 => [
                'Barrio Colombia',
                'Simesa',
                'Villa Carlota',
                'Castropol',
                'Lalinde',
                'Las Lomas N°1',
                'Las Lomas N°2',
                'Altos del Poblado',
                'El Tesoro',
                'Los Naranjos',
                'Los Balsos N°1',
                'San Lucas',
                'El Diamante N°2',
                'El Castillo',
                'Los Balsos N°2',
                'Alejandría',
                'La Florida',
                'El Poblado',
                'Manila',
                'Astorga',
                'Patio Bonito',
                'La Aguacatala',
                'Santa María de Los Ángeles',
            ],
            15 => [
                'Tenche',
                'Trinidad',
                'Santa Fé',
                'Parque Juan Pablo II',
                'Campo Amor',
                'Noel',
                'Cristo Rey',
                'Guayabal',
                'La Colina',
                'El Rodeo',
            ],
            16 => [
                'Fátima',
                'Rosales',
                'Belén',
                'Granada',
                'San Bernardo',
                'Las Playas',
                'Diego Echavarría',
                'La Mota',
                'La Hondonada',
                'El Rincón',
                'La Loma de Los Bernal',
                'La Gloria',
                'Altavista',
                'La Palma',
                'Los Alpes',
                'Las Violetas',
                'Las Mercedes',
                'Nueva Villa de Aburrá',
                'Miravalle',
                'El Nogal - Los Almendros',
                'Cerro Nutibara',
            ],
        ];

        foreach ($barriosPorComuna as $numero => $barrios) {
            foreach ($barrios as $barrio) {
                DB::table('t1_barrio')->insert([
                    'descripcion' => $barrio,
                    'estado' => '1',
                    'comuna_id' => $comunaIds[$numero],
                ]);
            }
        }
    }

    private function medellinId(): int
    {
        $row = DB::table('t1_municipio')->where('descripcion', 'MEDELLÍN')->first();
        if (!$row) {
            $row = DB::table('t1_municipio')->where('descripcion', 'LIKE', '%MEDELL%')->first();
        }
        return $row->id;
    }
}
